version: '3'

services:
  traefik-reverse:
    image: traefik:v2.9
    restart: always
    networks:
      - traefik-public
    ports:
      - "80:80"
      - "443:443"
      # # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml
      - ./acme.json:/acme.json
      - ./dynamic-conf.yml:/dynamic-conf.yml
      - ./traefik-dashboard-users:/traefik-dashboard-users
    environment:
      - TZ=Europe/Paris
    logging:
      driver: "json-file"
      options:
        max-file: "1"
        max-size: "2048m"

    deploy:
      placement:
        constraints:
          # Make the traefik service run only on the node with this label
          # as the node with it has the volume for the certificates
          - node.labels.traefik-public.traefik-public-certificates == true
    labels:
      #- traefik.constraint-label=traefik-public
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`traefik.mete0r.fr`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
      - traefik.http.routers.dashboard.tls=true
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.tls.certresolver=default
      - traefik.http.routers.dashboard.middlewares=dashboard-auth
      - traefik.http.middlewares.dashboard-auth.basicauth.usersfile=/traefik-dashboard-users
      - traefik.http.services.dashboard.loadbalancer.server.port=8080

networks:
  traefik-public:
    external: true